### PR TITLE
Typo Search

### PR DESCRIPTION
**Pull request by brookeclouston**
relates to Redmine Support #12203,#12463,#12464, created new single file for previous 4 files needed for preforming typo searches within the taxon and geography tree

### CODE REVIEW

**Comment by kcranston** [comment]
Can you take a look at this, @brookeclouston ? Tests are failing for me:

```
(env) ➜  specify-scripts git:(TypoSearch) ✗ python test_specifytreebuilder.py               
......F...F.
======================================================================
FAIL: test_check_author_brackets (__main__.TestDatabase)
tests to confirm that the check author function works if the first letter of the author is a bracket
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_specifytreebuilder.py", line 77, in test_check_author_brackets
    self.assertEqual(expected, actual)
AssertionError: {('foo', 'b'): [('123', '[bar]')]} != {('foo', '['): [('123', '[bar]')]}
- {('foo', 'b'): [('123', '[bar]')]}
?           ^

+ {('foo', '['): [('123', '[bar]')]}
?           ^


======================================================================
FAIL: test_rank_dict (__main__.TestDatabase)
tests to confirm the dictionary created is pulling the correct data in the correct format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_specifytreebuilder.py", line 43, in test_rank_dict
    self.assertDictEqual(expected,actual)
AssertionError: {'1': [('a', 'b')], '2': [('d', 'e'), ('g', 'h')], '3': [('j', 'k')]} != {'1': [], '2': [], '3': []}
- {'1': [('a', 'b')], '2': [('d', 'e'), ('g', 'h')], '3': [('j', 'k')]}
+ {'1': [], '2': [], '3': []}

----------------------------------------------------------------------
Ran 12 tests in 0.020s

FAILED (failures=2)
```

You will want to pull before running locally, because I had to fix up some conflicts with dev.

**Comment by brookeclouston** [comment]
The reason why the test is failing is because the version of specifytreebuilder.py the test was written for is not the version that is in this branch (and being tested on). The correct version of the original script and its test script is in the dev branch

**Comment by brookeclouston** [comment]
The scripts that should be merged from this branch into dev are: 
`TypoSearch.py`
`test_TypoSearch.py`

**Comment by kcranston** [comment]
Should the `LocalityTypoSearch.py` file still exist after merging this?

**Comment by brookeclouston** [comment]
No, `LocalityTypoSearch.py`,`GeographyTypoSearch.py`, `TaxonTypoSearch.py` and `GenusTypoSearch.py` should not exist after the merge (they are all replaced by  `TypoSearch.py`).

**Comment by kcranston** [comment]
How did you decide on distance <= 2 as the threshold? How do the results change if the limit is different?

**Comment by brookeclouston** [comment]
I chose <= 2 because that seemed to be the LD value that would avoid the most 'trivial' typo mistakes (ie 'Begonia bakerii' and 'Begonia ravenii' have a LD of 3 and are obviously not typos ). 
In the case of a GenusTypo search, I experimented with a range of <= 3 and it returned 8594 flagged possible typos, compared to the 1919 flagged possible typos when the LD is restricted to <=2.
 To answer your question, <= 2 was what _I thought_ was appropriate given the information in the names. 
I can add in the option to define what a typo is (LD value) as a command line argument if that works better.

**Pull request merged**
